# Generated by Django 4.0.3 on 2022-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
