# Generated by Django 4.0.3 on 2022-03-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pictutre',
            new_name='picture',
        ),
    ]
