# Generated by Django 4.0.3 on 2022-03-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_count_book_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
