# Generated by Django 4.0.3 on 2022-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_discount_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('received', 'received')], default='open', max_length=10),
        ),
    ]
