# Generated by Django 4.0.3 on 2022-03-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
