# Generated by Django 4.0.3 on 2022-03-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderitem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('receive', 'receive'), ('received', 'received')], default='open', max_length=10),
        ),
    ]
